In [2]:
import numpy as np

In [7]:
dados = np.array([1,6,8,9,33,0,99])
dados


array([ 1,  6,  8,  9, 33,  0, 99])

In [75]:
dados.size

6

## <b>array.T</b>
* transforma linhas em colunas


In [47]:
km = [193300,98556,35543]
ano = [2000, 1980, 2021]

info_carros = np.array([km, ano])

In [ ]:
info_carros

In [ ]:
info_carros.T

In [ ]:
contador = np.arange(10)
contador

In [ ]:
contador.reshape((5,2), order='C')

<h2><b> Resize </b></h2>
 - criando nova linha em uma array

In [48]:
new_infos = info_carros.copy()

In [49]:
new_infos

array([[193300,  98556,  35543],
       [  2000,   1980,   2021]])

In [52]:
new_infos.resize((3, 3), refcheck=False)
new_infos

array([[193300,  98556,  35543],
       [  2000,   1980,   2021],
       [     0,      0,      0]])

* Adicionado km média por carro

In [54]:
new_infos[2] = new_infos[0]/ (2022 - new_infos[1])
new_infos

array([[193300,  98556,  35543],
       [  2000,   1980,   2021],
       [  8786,   2346,  35543]])

# <b>Estatística simples com numpy</b>

In [56]:
anos = np.loadtxt('carros-anos.txt', dtype=int)
km = np.loadtxt('carros-km.txt')
valor = np.loadtxt('carros-valor.txt')

In [62]:
anos.shape

(258,)

In [63]:
dataset= np.column_stack((anos, km, valor))
dataset
dataset.shape

(258, 3)

* Média dos km

In [64]:
np.mean(dataset[:,1])

44499.41472868217

In [66]:
np.mean(dataset[:, 2])


98960.51310077519

In [68]:
np.sum(dataset, axis=0)

array([  517938.        , 11480849.        , 25531812.37999999])

* Somatório dos valores dos veículos

In [72]:
np.sum(dataset[:, 2])

25531812.38